# Generated by Django 5.1.4 on 2024-12-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='purchased_score',
            new_name='purchased_scores',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='type',
            new_name='score_type',
        ),
        migrations.AlterField(
            model_name='score',
            name='youtube_id_video',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
