# Generated by Django 5.1.4 on 2024-12-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0002_rename_purchased_score_profile_purchased_scores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='Arranger',
            new_name='arranger',
        ),
    ]
