# Generated by Django 5.1.4 on 2024-12-10 18:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0003_rename_arranger_score_arranger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='scores/'),
        ),
        migrations.AlterField(
            model_name='score',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.9900000000000002131628207280300557613372802734375'), max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
