# Generated by Django 5.1.4 on 2024-12-11 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0004_alter_score_file_alter_score_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='published_key',
            field=models.CharField(choices=[('C', 'C major'), ('A-', 'A minor'), ('G', 'G major (1 sharp)'), ('E-', 'E minor (1 sharp)'), ('D', 'D major (2 sharps'), ('B-', 'B minor (2 sharps)'), ('A', 'A major (3 sharps)'), ('F#-', 'F# minor (3 sharps)'), ('E', 'E major (4 sharps)'), ('C#-', 'C# minor (4 sharps)'), ('B', 'B major (5 sharps)'), ('G#-', 'G# minor (5 sharps)'), ('F#', 'F# major (6 sharps)'), ('D#-', 'D# minor (6 sharps)'), ('C#', 'C# major (7 sharps)'), ('A#-', 'A# minor (7 sharps)'), ('F', 'F major (1 flat'), ('D-', 'D minor (1 flat)'), ('Bb', 'Bb major (2 flats)'), ('G-', 'G minor (2 flats)'), ('Eb', 'Eb major (3 flats)'), ('C-', 'C minor (3 flats)'), ('Ab', 'Ab major (4 flats)'), ('F-', 'F minor (4 flats)'), ('Db', 'Db major (5 flats)'), ('Bb-', 'Bb minor (5 flats)'), ('Gb', 'Gb major (6 flats)'), ('Eb-', 'Eb minor (6 flats)'), ('Cb', 'Cb major (7 flats)'), ('Ab-', 'Ab minor (7 flats)')], default='insert key', max_length=50),
        ),
    ]
