# Generated by Django 5.1.4 on 2024-12-12 14:50

import django.core.validators
import sheetmusic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0006_rename_pages_number_score_pages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='youtube_id_video',
            new_name='youtube_video_link',
        ),
        migrations.AddField(
            model_name='score',
            name='cover',
            field=models.FileField(blank=True, upload_to='score/covers/'),
        ),
        migrations.AlterField(
            model_name='score',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='scores/files/', validators=[sheetmusic.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='score',
            name='pages',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
