# Generated by Django 5.1.4 on 2024-12-12 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0007_rename_youtube_id_video_score_youtube_video_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='score/covers/'),
        ),
        migrations.AlterField(
            model_name='score',
            name='pages',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
