# Generated by Django 5.1.4 on 2024-12-14 18:47

import sheetmusic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0010_alter_score_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='file',
            field=models.FileField(upload_to='media/scores/files/', validators=[sheetmusic.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='score',
            name='youtube_video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
