# Generated by Django 5.1.4 on 2024-12-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0011_alter_score_file_alter_score_youtube_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='media/profiles/profile_imgs'),
        ),
    ]
