# Generated by Django 5.1.4 on 2024-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0013_profile_mantra'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_account_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='x_account_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_account_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
