# Generated by Django 5.1.4 on 2024-12-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0014_profile_instagram_account_id_profile_x_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, default='media/profiles/profile_imgs/profile-default.1024x1023.png', null=True, upload_to='media/profiles/profile_imgs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='purchased_scores',
            field=models.ManyToManyField(blank=True, related_name='purchased_scores', through='sheetmusic.Copy', to='sheetmusic.score'),
        ),
        migrations.AlterField(
            model_name='score',
            name='arranger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='sheetmusic.profile'),
        ),
    ]
