# Generated by Django 5.1.4 on 2024-12-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0016_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_scores',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='sheetmusic.score'),
        ),
    ]
