# Generated by Django 5.1.4 on 2024-12-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0017_profile_liked_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='media/profiles/profile_imgs'),
        ),
    ]
