# Generated by Django 5.1.4 on 2024-12-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0018_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, default='media/profiles/profile_imgs/profile-default.1024x1023.png', null=True, upload_to='media/profiles/profile_imgs'),
        ),
    ]
