# Generated by Django 5.1.4 on 2024-12-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0021_billingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='in_shopping_cart', to='sheetmusic.score'),
        ),
    ]
