# Generated by Django 5.1.4 on 2024-12-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0022_profile_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='billing_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='postal_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
