# Generated by Django 5.1.4 on 2025-01-02 10:55

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0023_alter_billingprofile_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
