# Generated by Django 5.1.4 on 2025-01-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0024_alter_billingprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='country',
            field=models.CharField(blank='(select country)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
