# Generated by Django 5.1.4 on 2025-01-02 14:42

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0025_alter_billingprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
