# Generated by Django 5.1.4 on 2025-01-02 14:43

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0026_billingprofile_province_alter_billingprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
