# Generated by Django 5.1.4 on 2025-01-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0027_alter_billingprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='score_receiving_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
