# Generated by Django 5.1.4 on 2025-01-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0028_billingprofile_score_receiving_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='score_receiving_email',
            new_name='receiving_email',
        ),
        migrations.RemoveField(
            model_name='billingprofile',
            name='postal_code',
        ),
    ]
